In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nickdoulos/greeces-earthquakes/Earthquakes_v3.csv

In [5]:
df = pd.read_csv('/kaggle/input/datasets/nickdoulos/greeces-earthquakes/Earthquakes_v3.csv')
df.head()

          DATETIME    LAT   LONG  DEPTH  MAGNITUDE
0   1/7/1965 10:22  36.50  26.50     10        5.3
1   1/10/1965 8:02  39.25  22.25     10        4.9
2  1/12/1965 17:26  37.00  22.00     10        4.0
3  1/15/1965 14:56  36.75  21.75     10        4.5
4   3/9/1965 19:16  39.00  24.00     10        4.2

In [6]:
import datetime as dt

In [11]:
hozir = dt.datetime.now()

In [12]:
hozir

datetime.datetime(2026, 8, 7, 20, 34, 16, 176162)

In [13]:
print(hozir)

2026-08-07 20:34:16.176162

In [15]:
type(hozir)

datetime.datetime

In [16]:
hozir.hour

20

In [18]:
hozir.weekday()

4

In [19]:
df.head()

          DATETIME    LAT   LONG  DEPTH  MAGNITUDE
0   1/7/1965 10:22  36.50  26.50     10        5.3
1   1/10/1965 8:02  39.25  22.25     10        4.9
2  1/12/1965 17:26  37.00  22.00     10        4.0
3  1/15/1965 14:56  36.75  21.75     10        4.5
4   3/9/1965 19:16  39.00  24.00     10        4.2

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285118 entries, 0 to 285117
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATETIME   285118 non-null  object
 1   LAT        285118 non-null  float64
 2   LONG       285118 non-null  float64
 3   DEPTH      285118 non-null  int64
 4   MAGNITUDE  285118 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 10.9+ MB

In [21]:
df['DATETIME'].str.len()

0         14
1         14
2         15
3         15
4         14
          ..
285113    15
285114    15
285115    15
285116    15
285117    15
Name: DATETIME, Length: 285118, dtype: int64

In [22]:
df['DATETIME'].str.len().value_counts()

DATETIME
15    110444
14    105546
16     26143
13     25761
19     17224
Name: count, dtype: int64

In [23]:
df['DATETIME'] = pd.to_datetime(df['DATETIME'], errors='coerce')

In [26]:
df['DATETIME'].dtype

dtype('<M8[ns]')

In [27]:
df.head()

             DATETIME    LAT   LONG  DEPTH  MAGNITUDE
0 1965-01-07 10:22:00  36.50  26.50     10        5.3
1 1965-01-10 08:02:00  39.25  22.25     10        4.9
2 1965-01-12 17:26:00  37.00  22.00     10        4.0
3 1965-01-15 14:56:00  36.75  21.75     10        4.5
4 1965-03-09 19:16:00  39.00  24.00     10        4.2

In [28]:
df['DATETIME'].value_counts()

DATETIME
2021-10-04 22:37:00    4
2011-01-27 10:13:00    4
2021-03-02 00:54:00    4
2023-10-14 02:25:00    4
2021-03-03 13:06:00    4
                      ..
2012-01-24 21:35:00    1
2012-01-24 21:40:00    1
2012-01-24 23:07:00    1
2012-01-24 23:08:00    1
2012-01-24 19:52:00    1
Name: count, Length: 262277, dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285118 entries, 0 to 285117
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATETIME   267894 non-null  datetime64[ns]
 1   LAT        285118 non-null  float64
 2   LONG       285118 non-null  float64
 3   DEPTH      285118 non-null  int64
 4   MAGNITUDE  285118 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 10.9 MB

In [33]:
df.loc[0, 'DATETIME']

Timestamp('1965-01-07 10:22:00')