In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/botirTurgonboyev/praktikum_datasets/refs/heads/main/MOCK_USER_DATA.csv', index_col=0)
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [16]:
df.describe()

               age
count   100.000000
mean    145.660000
std     565.631411
min     -85.000000
25%      22.750000
50%      53.500000
75%      84.250000
max    4444.000000

In [17]:
df.age>123

id
1      False
2      False
3       True
4      False
5      False
       ...
96     False
97     False
98     False
99     False
100     True
Name: age, Length: 100, dtype: bool

In [18]:
df[df.age>123]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

In [19]:
indx = df[df.age>123].index
indx

Index([3, 39, 47, 49, 65, 80, 100], dtype='int64', name='id')

In [20]:
df.drop(index=indx, inplace=True)

In [21]:
df

   first_name   last_name                           email       gender  age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female   48
6       Glynn      Ebbing          gebbing5@rakuten.co.jp  Genderfluid   77
..        ...         ...                             ...          ...  ...
95      Byron  Whittleton   bwhittleton2m@theatlantic.com   Non-binary    2
96       Baxy       Marcu        bmarcu2n@list-manage.com      Agender   64
97     Kattie     Claxson          kclaxson2o@booking.com       Female   18
98       Clem     Fullerd  cfullerd2p@creativecommons.org     Bigender   55
99  Desdemona     Jurasek        djurasek2q@aboutads.info  Genderfluid   46

[93 rows x 5 columns]

In [22]:
df[df.age<0]

   first_name  last_name                           email       gender  age
id
11     Elijah      Heine                eheinea@imdb.com     Bigender  -85
19      Luisa  Bradborne            lbradbornei@fema.gov       Female  -75
21      Levin     Worner                lwornerk@ihg.com  Genderqueer  -43
33   Ebenezer    Greeves           egreevesw@myspace.com         Male  -26
38       Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer  -42
90  Zachariah      Meins            zmeins2h@weather.com         Male  -69

In [23]:
df['age'] = df['age'].apply(np.abs)

In [24]:
df

   first_name   last_name                           email       gender  age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary    1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male   91
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid    6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female   48
6       Glynn      Ebbing          gebbing5@rakuten.co.jp  Genderfluid   77
..        ...         ...                             ...          ...  ...
95      Byron  Whittleton   bwhittleton2m@theatlantic.com   Non-binary    2
96       Baxy       Marcu        bmarcu2n@list-manage.com      Agender   64
97     Kattie     Claxson          kclaxson2o@booking.com       Female   18
98       Clem     Fullerd  cfullerd2p@creativecommons.org     Bigender   55
99  Desdemona     Jurasek        djurasek2q@aboutads.info  Genderfluid   46

[93 rows x 5 columns]

In [25]:
df[df.age<0]

Empty DataFrame
Columns: [first_name, last_name, email, gender, age]
Index: []

In [26]:
df.gender.value_counts()

gender
Male           21
Bigender       12
Female         11
Genderfluid    11
Non-binary     10
Genderqueer    10
Agender         9
Polygender      9
Name: count, dtype: int64

In [29]:
df = df[df.gender.isin(['Male', 'Female'])]

In [30]:
df

   first_name     last_name                         email  gender  age
id
2     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
19      Luisa     Bradborne          lbradbornei@fema.gov  Female   75
22        Ray         Padly           rpadlyl@twitpic.com    Male   85
26   Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
29      Biron      Acklands        backlandss@comsenz.com    Male   13
33   Ebenezer       Greeves         egreevesw@myspace.com    Male   26
34     Brooks          Vose             bvosex@amazon.com  Female   34
36        Axe       Arundel           aarundelz@yahoo.com  Female   14
43       Bili     Swetenham        bswetenham16@europa.eu    Male   23
46     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
58     Brynna        Worsom              bworsom1l@wp.com    Male   66
61       Page       Merrell     pmerrell1o@slideshare.net    Male    1
62     Kennan         Visco          kvisco1p@jiathis.com  Female   94
63   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
67     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
70      Ambur        Aickin           aaickin1x@about.com    Male   60
72   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
74      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
76      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
77     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
81       Alex         Darth    adarth28@ezinearticles.com  Female   98
86    Rogerio          Akid           rakid2d@latimes.com  Female    3
87      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
88       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
90  Zachariah         Meins          zmeins2h@weather.com    Male   69
91      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
94     Sheree        Cockin     scockin2l@accuweather.com  Female   94
97     Kattie       Claxson        kclaxson2o@booking.com  Female   18

In [31]:
#Tayyor