In [24]:
import pandas as pd

In [25]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

In [26]:
df.duplicated().sum()

np.int64(15)

In [27]:
sum(df.duplicated())

15

In [28]:
df.drop_duplicates()

                    pop2021     area
country
Macau               658.394       30
Monaco               39.511        2
Burundi           12255.433    27834
Singapore          5896.686      710
Hong Kong          7552.810     1104
...                     ...      ...
Namibia            2587.344   825615
Western Sahara      611.875   266000
Mongolia           3329.289  1564110
Falkland Islands      3.533    12173
Greenland            56.877  2166086

[232 rows x 2 columns]

In [29]:
df.drop_duplicates(inplace=True)

In [30]:
df.shape

(232, 2)

In [31]:
df.sort_index(inplace=True)

In [32]:
df

                     pop2021     area
country
Afghanistan        39835.428   652230
Albania             2872.933    28748
Algeria            44616.624  2381741
American Samoa        55.100      199
Andorra               77.355      468
...                      ...      ...
Wallis and Futuna     11.094      142
Western Sahara       611.875   266000
Yemen              30490.640   527968
Zambia             18920.651   752612
Zimbabwe           15092.171   390757

[232 rows x 2 columns]

In [33]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [34]:
df.loc['India']

pop2021    1393409.038
area       3287590.000
Name: India, dtype: float64

In [35]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [36]:
population = df.pop2021

In [37]:
guruh = pd.cut(population, bins)

In [38]:
guruh.value_counts()

pop2021
(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [39]:
guruh

country
Afghanistan          (30000, 50000]
Albania               (1000, 10000]
Algeria              (30000, 50000]
American Samoa            (0, 1000]
Andorra                   (0, 1000]
                          ...
Wallis and Futuna         (0, 1000]
Western Sahara            (0, 1000]
Yemen                (30000, 50000]
Zambia               (10000, 30000]
Zimbabwe             (10000, 30000]
Name: pop2021, Length: 232, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [40]:
df['guruh'] = guruh
df

                     pop2021     area           guruh
country
Afghanistan        39835.428   652230  (30000, 50000]
Albania             2872.933    28748   (1000, 10000]
Algeria            44616.624  2381741  (30000, 50000]
American Samoa        55.100      199       (0, 1000]
Andorra               77.355      468       (0, 1000]
...                      ...      ...             ...
Wallis and Futuna     11.094      142       (0, 1000]
Western Sahara       611.875   266000       (0, 1000]
Yemen              30490.640   527968  (30000, 50000]
Zambia             18920.651   752612  (10000, 30000]
Zimbabwe           15092.171   390757  (10000, 30000]

[232 rows x 3 columns]

In [41]:
population.head()

country
Afghanistan       39835.428
Albania            2872.933
Algeria           44616.624
American Samoa       55.100
Andorra              77.355
Name: pop2021, dtype: float64

In [42]:
df.head()

                  pop2021     area           guruh
country
Afghanistan     39835.428   652230  (30000, 50000]
Albania          2872.933    28748   (1000, 10000]
Algeria         44616.624  2381741  (30000, 50000]
American Samoa     55.100      199       (0, 1000]
Andorra            77.355      468       (0, 1000]

In [53]:
names = ['arzon', "o'rtacha", 'qimmatroq', 'qimmat', 'juda qimmat', 'bisnes', 'premer']

In [54]:
df2 = pd.cut(df.pop2021, bins, labels=names)

In [56]:
df2.value_counts()

pop2021
arzon          72
o'rtacha       68
qimmatroq      44
qimmat         19
juda qimmat    15
bisnes         11
premer          3
Name: count, dtype: int64

In [57]:
df3 = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df3.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [60]:
df3.describe()

       wheel-base      length  horsepower  average-mileage         price
count   61.000000   61.000000   61.000000        61.000000     58.000000
mean    98.481967  173.098361  107.852459        25.803279  15387.000000
std      6.679234   14.021846   53.524398         8.129821  11320.259841
min     88.400000  141.100000   48.000000        13.000000   5151.000000
25%     94.500000  159.100000   68.000000        19.000000   6808.500000
50%     96.300000  171.200000  100.000000        25.000000  11095.000000
75%    101.200000  177.300000  123.000000        31.000000  18120.500000
max    120.900000  208.100000  288.000000        47.000000  45400.000000

In [61]:
narx = [0, 15000, 25000, 46000]

In [62]:
range = pd.cut(df3.price, narx)

In [63]:
range

index
0         (0, 15000]
1     (15000, 25000]
2     (15000, 25000]
3         (0, 15000]
4     (15000, 25000]
           ...
81        (0, 15000]
82        (0, 15000]
86        (0, 15000]
87        (0, 15000]
88        (0, 15000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 15000] < (15000, 25000] < (25000, 46000]]

In [64]:
range.value_counts()

price
(0, 15000]        36
(25000, 46000]    12
(15000, 25000]    10
Name: count, dtype: int64

In [65]:
groups = ['arzon', "o'rtacha", 'qimmat']

In [66]:
range = pd.cut(df3.price, narx, labels=groups)

In [67]:
range.value_counts()

price
arzon       36
qimmat      12
o'rtacha    10
Name: count, dtype: int64

In [69]:
df3['group'] = range

In [70]:
df3

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,group
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,arzon
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,o'rtacha
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0,o'rtacha
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0,arzon
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0,o'rtacha
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0,arzon
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0,arzon
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0,arzon
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0,arzon
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0,arzon

In [71]:
#bir xil guruhlash
range = pd.qcut(df3.price, 3)
range.value_counts()

price
(16430.0, 45400.0]    20
(5150.999, 7295.0]    19
(7295.0, 16430.0]     19
Name: count, dtype: int64

In [72]:
range = pd.qcut(df3.price,4)
range.value_counts()

price
(5150.999, 6808.5]    15
(18120.5, 45400.0]    15
(6808.5, 11095.0]     14
(11095.0, 18120.5]    14
Name: count, dtype: int64

In [73]:
range = pd.qcut(df3.horsepower, 3)
range.value_counts()

horsepower
(47.999, 70.0]    24
(111.0, 288.0]    20
(70.0, 111.0]     17
Name: count, dtype: int64